
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Strong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - microservices-net
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
 
  # -------------------- RABBITMQ -------------------- #
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      # nạp sẵn exchange/queue/binding
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: >-
        -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - microservices-net

  # -------------------- PAYMENT SERVICE -------------------- #
  payment-service:
    build: ./payment-service
    volumes:
      - ./payment-service:/app
    container_name: payment-service
    restart: always
    environment:
      - PORT=4002
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Strong@Pass123
      - DB_NAME=Mutrapro_Payment
    ports:
      - "4002:4002"
    networks:
      - microservices-net
    depends_on:
      - rabbitmq
      - sqlserver

  # -------------------- ORDER SERVICE -------------------- #
  order-service:
    build: ./order-service
    container_name: order-service
    restart: always
    environment:
      - PORT=4001
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Strong@Pass123
      - DB_NAME=Mutrapro_Order
    ports:
      - "4001:4001"
    networks:
      - microservices-net
    depends_on:
      - rabbitmq
      - sqlserver

  # -------------------- NOTIFICATION SERVICE -------------------- #
  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    environment:
      - PORT=4003
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Strong@Pass123
      - DB_NAME=Mutrapro_Notification
    ports:
      - "4003:4003"
    networks:
      - microservices-net
    depends_on:
      - rabbitmq
      - sqlserver

  # -------------------- MEDIA SERVICE -------------------- #
  media-service:
    build: ./media-service
    container_name: media-service
    restart: always
    environment:
      - PORT=4004
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Strong@Pass123
      - DB_NAME=Mutrapro_Media
    ports:
      - "4004:4004"
    networks:
      - microservices-net
    depends_on:
      - rabbitmq
      - sqlserver
# -------------------- MANAGEMENT STUDIO SERVICE -------------------- #
  management-studio-service:
    build: ./management-studio-service
    container_name: management-studio-service
    restart: always
    environment:
      - PORT=4005
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Strong@Pass123
      - DB_NAME=Mutrapro_ManagementStudio
    ports:
      - "4005:4005"
    networks:
      - microservices-net
    depends_on:
      - rabbitmq
      - sqlserver

  # -------------------- USER (DJANGO) SERVICE -------------------- #
  user-service:
      build: ./user-service
      volumes:
        - ./user-service:/app
      container_name: user-service
      restart: always
      environment:
        - DJANGO_SETTINGS_MODULE=userService.settings
        - DB_ENGINE=mssql
        - DB_HOST=sqlserver
        - DB_PORT=1433
        - DB_USER=sa
        - DB_PASSWORD=Strong@Pass123
        - DB_NAME=Mutrapro_User
      ports:
        - "8005:8000"
      networks:
        - microservices-net
      depends_on:
        - rabbitmq
        - sqlserver

  # -------------------- GATEWAY SERVICE -------------------- #
  gateway:
    build: ./gate-way
    volumes:
      - ./gate-way:/app
    container_name: gateway
    restart: always
    environment:
      - PORT=8000
      - PAYMENT_SERVICE_URL=http://payment-service:4002
      - NOTIFICATION_SERVICE_URL=http://notification-service:4003
      - ORDER_SERVICE_URL=http://order-service:4001
      - MEDIA_SERVICE_URL=http://media-service:4004
      - MANAGEMENT_STUDIO_SERVICE_URL=http://management-studio-service:4005
      - USER_SERVICE_URL=http://user-service:8005
    ports:
      - "8000:8000"
    networks:
      - microservices-net
    depends_on:
      - payment-service
      - rabbitmq

networks:
  microservices-net:
    driver: bridge

volumes:
    sqlserver-data: